cloudflared:
  cert:
    nickysemenza.com: |
      -----BEGIN PRIVATE KEY-----
      MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgWWKBsyAqPpSXlzib
      zpBzXvM4M93EPGpGUL/IdyoIxbKhRANCAASAGj9R1Ytm7HVK5mc8doR9g0neMRUL
      Q2qrBDosybL/kTW7ey0reW9Y182ZyBVIcUz3OltA7wjbBM+bsUEsEmOE
      -----END PRIVATE KEY-----
      -----BEGIN CERTIFICATE-----
      MIIDKzCCAtGgAwIBAgITWC35Iw9oCGwpJHOvqPfxA6ZZAzAKBggqhkjOPQQDAjCB
      jzELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNh
      biBGcmFuY2lzY28xGTAXBgNVBAoTEENsb3VkRmxhcmUsIEluYy4xODA2BgNVBAsT
      L0Nsb3VkRmxhcmUgT3JpZ2luIFNTTCBFQ0MgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
      MB4XDTE5MDEyMjA2NTYwMFoXDTM0MDExODA2NTYwMFowYjEZMBcGA1UEChMQQ2xv
      dWRGbGFyZSwgSW5jLjEdMBsGA1UECxMUQ2xvdWRGbGFyZSBPcmlnaW4gQ0ExJjAk
      BgNVBAMTHUNsb3VkRmxhcmUgT3JpZ2luIENlcnRpZmljYXRlMFkwEwYHKoZIzj0C
      AQYIKoZIzj0DAQcDQgAEgBo/UdWLZux1SuZnPHaEfYNJ3jEVC0NqqwQ6LMmy/5E1
      u3stK3lvWNfNmcgVSHFM9zpbQO8I2wTPm7FBLBJjhKOCATYwggEyMA4GA1UdDwEB
      /wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDAYDVR0TAQH/
      BAIwADAdBgNVHQ4EFgQUxnDPDPRtOBztRAW/z3rp45LhNBswHwYDVR0jBBgwFoAU
      hTBdOypw1O3VkmcH/es5tBoOOKcwRAYIKwYBBQUHAQEEODA2MDQGCCsGAQUFBzAB
      hihodHRwOi8vb2NzcC5jbG91ZGZsYXJlLmNvbS9vcmlnaW5fZWNjX2NhMC8GA1Ud
      EQQoMCaCEioubmlja3lzZW1lbnphLmNvbYIQbmlja3lzZW1lbnphLmNvbTA8BgNV
      HR8ENTAzMDGgL6AthitodHRwOi8vY3JsLmNsb3VkZmxhcmUuY29tL29yaWdpbl9l
      Y2NfY2EuY3JsMAoGCCqGSM49BAMCA0gAMEUCIBwFAjb/Femnquav3a2QOuu2vzgC
      PbFxT9vuPQ5dFUfDAiEAjipPKOP1fd7ibe4pcL758N7oSD4aztuQQcPRWDdew7Y=
      -----END CERTIFICATE-----
      -----BEGIN ARGO TUNNEL TOKEN-----
      MDY3ZDJmMTlkMjhlODEyMjIzMjM2ZjFkMTQ2NTExZjIKdjEuMC00Mjg4N2IyYTQ4
      MjQwYmEwYmY4NDhjMTkzODEzNzhkOTFhZjE4ZWVhNTIxN2IxMGJiNmRhMWFmOTk3
      MDQyY2MyLTY3YjJlMTZkMzIzZTQ3NGVmNjRhMDNjODBkYzJhYzk1MTgzNjQyZDMy
      OGRhZTBjMjY3NjhlM2JiMDc1N2FkZDRhMTllYzE5MDA2YTAyMWI0OGU1OWMzNzAw
      YzMxNzJiNTI0MzhkMjJlNWJhNGM3ZDVhZTNmMDA1NTEyNzA4NWVmLWJmNTM2ZDgz
      Y2RiYWVlNDE2MTAyNDBhZjRiODNmNzU0Zjc3ZDU3MzVmMzk0NTkyMThhYjU3MGJh
      YjA1ZWIxZTg=
      -----END ARGO TUNNEL TOKEN-----